clinic/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.general.urls')),
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

apps/symptom/models.py
from django.db import models
from solo.models import SingletonModel
from apps.accounts.models import User
from django.utils import timezone
import uuid
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone


# Create your models here.

class Agency(SingletonModel):
    name = models.CharField(max_length=150)
    address = models.CharField(max_length=150)
    city = models.CharField(max_length=150)
    state = models.CharField(max_length=70)
    zip = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=40)
    fax = models.CharField(max_length=40)

    class Meta:
        verbose_name = "Agency"
        verbose_name_plural = "Agencys"

    def __str__(self):
        return self.name





class Medication(models.Model):
    name = models.CharField(max_length=50)
    quantity = models.PositiveIntegerField()
    customer = models.ForeignKey(
        'Customer', 
        on_delete=models.CASCADE, 
        related_name='medications'
    )

    class Meta:
        verbose_name = "Medication"
        verbose_name_plural = "Medications"

    def __str__(self):
        return f"{self.name} ({self.quantity}mg)"
    
class Symptom(models.Model):
    code = models.CharField(max_length=255, unique=True)
    description = models.TextField(max_length=1000)
    

    class Meta:
        verbose_name = "Symptom"
        verbose_name_plural = "Symptoms"

    def __str__(self):
        return self.code

class Insurance(models.Model):
    abbreviated = models.CharField(max_length=15, unique=True)
    name = models.CharField(max_length=255, unique=True)
    available = models.BooleanField(default=True)
    auth_required = models.BooleanField(default=True)
    

    class Meta:
        verbose_name = "Insurance"
        verbose_name_plural = "Insurances"

    def __str__(self):
        return self.name
    
class Diagnostic(models.Model):
    code = models.CharField(max_length=15, unique=True)
    description = models.TextField(max_length=500)
    # customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='diagnostics', null=True, blank=True)
    
    class Meta:
        verbose_name = "Diagnostic"
        verbose_name_plural = "Diagnostics"

    def __str__(self):
        return self.code


class Customer(models.Model):
    case_no = models.CharField(max_length=40, unique=True)
    create_at = models.DateField(auto_created=True,default=timezone.now)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    address = models.TextField(max_length=500)
    contact_no = models.CharField(max_length=20, null=True, blank=True)
    home_phone = models.CharField(max_length=20, null=True, blank=True)
    movile = models.CharField(max_length=20)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zip = models.CharField(max_length=50)
    dob = models.DateField(default=timezone.now)
    gender = models.CharField(max_length=50, default='M', choices=[('M', 'MALE'), ('F', 'FEMALE')])
    ssn = models.CharField(max_length=50, unique=True)
    mma = models.CharField(max_length=50, null=True, blank=True)
    medicaid_no = models.CharField(max_length=50, unique=True)
    medicare_no = models.CharField(max_length=50, null=True, blank=True)
    school = models.CharField(max_length=50, null=True, blank=True)
    grade = models.CharField(max_length=50, null=True, blank=True)
    race = models.CharField(max_length=50,default='W' ,choices=[('W', 'White'), ('AAB', 'African American Black'), ('API', 'Asian or Other Pacific Islander'), ('AIAN', 'American Indian-Alaskan Native'), ('O', 'Other')])
    referred_by = models.CharField(max_length=50, blank=True, null=True)
    referred_movile = models.IntegerField(blank=True, null=True)
    ethnicity = models.CharField(max_length=50,default='H',choices=[('H', 'Hispanic-latino'), ('NH', 'Non-Hispanic'), ('O', 'Other')])
    legal_guardian_full_name = models.CharField(max_length=80, null=True, blank=True)
    legal_guardian_relationship = models.CharField(max_length=80, null=True, blank=True)
    legal_guardian_phone_number = models.CharField(max_length=80, null=True, blank=True)
    legal_guardian_address = models.CharField(max_length=150, null=True, blank=True)
    legal_guardian_city = models.CharField(max_length=80, null=True, blank=True)
    legal_guardian_state = models.CharField(max_length=80, null=True, blank=True)
    legal_guardian_zip = models.CharField(max_length=80, null=True, blank=True)
    emergency_contact_person = models.CharField(max_length=80)
    emergency_contact_relationship = models.CharField(max_length=80)
    emergency_contact_phone_number = models.CharField(max_length=20)
    medicaid_gold_card = models.CharField(max_length=50, unique=True, null=True, blank=True)
    responsible_payee_last_name = models.CharField(max_length=50, null=True, blank=True, default="N/A")
    responsible_payee_first_name = models.CharField(max_length=50, null=True, blank=True, default="N/A")
    responsible_payee_address = models.CharField(max_length=150, null=True, blank=True, default="N/A")
    responsible_payee_city = models.CharField(max_length=80, null=True, blank=True, default="N/A")
    responsible_payee_state = models.CharField(max_length=80, null=True, blank=True, default="N/A")
    responsible_payee_zip = models.CharField(max_length=80, null=True, blank=True, default="N/A")
    responsible_payee_phone_number = models.CharField(max_length=20, null=True, blank=True, default="N/A")
    responsible_payee_fax = models.CharField(max_length=20, null=True, blank=True, default="N/A")
    no_dependences = models.PositiveIntegerField(default=0)
    family_year_income = models.DecimalField(max_digits=15, decimal_places=2, default=0.00)
    discount_standard_rate = models.DecimalField(max_digits=15, decimal_places=2, default=0.00,null=True, blank=True)
    sign = models.ImageField(upload_to='customer_sign',blank=True,null=True)
    insurance = models.ForeignKey(Insurance, on_delete=models.CASCADE)
    insurance_unit = models.PositiveIntegerField(default=0)
    insurance_init_date = models.DateField(null=True,blank=True)
    insurance_end_date = models.DateField(null=True,blank=True)
    diagnostic = models.ForeignKey(Diagnostic, on_delete=models.CASCADE)
    diagnostic_two = models.ForeignKey(Diagnostic, on_delete=models.CASCADE,null=True,blank=True, related_name='diagnostic_two_client')
    diagnostic_three = models.ForeignKey(Diagnostic, on_delete=models.CASCADE,null=True,blank=True, related_name='diagnostic_three_client')
    

    # def clean(self):
    #     from django.core.exceptions import ValidationError
    #     # Validar que la fecha no coincida con ninguna fecha de atención de terapeutas
    #     if self.treatment_plan_developed_date:
    #         # Verificar en terapias individuales
    #         individual_therapy_dates = IndividualTherapySection.objects.filter(
    #             customer=self,
    #             create_at=self.treatment_plan_developed_date
    #         )
    #         if individual_therapy_dates.exists():
    #             raise ValidationError(
    #                 {"treatment_plan_developed_date": "The treatment plan developed date cannot coincide with any therapist's session date."}
    #             )

    #         # Verificar en sesiones grupales
    #         group_therapy_dates = CustomerPSRSections.objects.filter(
    #             customer=self,
    #             section__create_at=self.treatment_plan_developed_date
    #         )
    #         if group_therapy_dates.exists():
    #             raise ValidationError(
    #                 {"treatment_plan_developed_date": "The treatment plan developed date cannot coincide with any group session date."}
    #             )

    #     super().clean()

 
    
    def save(self, *args, **kwargs):
        # if not self.code:
        #     self.code = uuid.uuid4().hex[:12].upper()  # Genera un código alfanumérico de 12 caracteres
        super(Customer, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Customer"
        verbose_name_plural = "Customers"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name }"
    
    @property
    def in_active(self):
        return True
    
    @property
    def years_old(self):
        from datetime import date
        today = date.today()
        age = today.year - self.dob.year
        if (today.month, today.day) < (self.dob.month, self.dob.day):
            age -= 1
        return age
    




class EncryptedFile(models.Model):
    file = models.FileField(upload_to='uploads/')
    file_type = models.CharField(max_length=10, choices=[('.docx', 'DOCX'), ('.doc', 'DOC'), ('.pdf', 'PDF'), ('.jpg', 'JPG'), ('.png', 'PNG')])
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uploaded_files')
    belongs_to = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='owned_files', default=1)
    encrypted_file = models.BinaryField()
    created_at = models.DateTimeField(default=timezone.now)
    process_start_date = models.DateField(default=timezone.now)

    def save(self, *args, **kwargs):
        # Asignar automáticamente el file_type basado en la extensión del archivo
        if self.file and not self.file_type:
            extension = self.file.name.split('.')[-1].lower()
            file_type_mapping = {
                'docx': '.docx',
                'doc': '.doc',
                'pdf': '.pdf',
                'jpg': '.jpg',
                'jpeg': '.jpg',  # Tratar JPEG como JPG
                'png': '.png',
            }
            self.file_type = file_type_mapping.get(extension, None)
        super(EncryptedFile, self).save(*args, **kwargs)

    def __str__(self):

templates/pages/customers/actions/components/partials/files.html
{% load static %}
{% load custom_filters %}

{% if tag_message %}
    <script>                
        Swal.fire({
            position: "top-center",
            icon: '{% if "error" in tags %}error{% elif "success" in tags %}success{% elif "info" in tags %}info{% elif "warning" in tags %}warning{% else %}question{% endif %}',
            title: "{{tag_message}}",
            showConfirmButton: false,
            timer: 3000
        });
    </script>
{% endif %}

{% for file in paginator|exclude_elegibility_files|exclude_psychiatric_evaluation_files|exclude_yearly_physical_files|exclude_suicide_risk_assessment_files|exclude_behavioral_health_evaluation_files|exclude_bio_psycho_social_assessment_files|exclude_brief_behavioral_health_assessment_files|exclude_discharge_summary_files|exclude_fars_files %}
    <div class="col-6 col-sm-4 col-xl-3">
        <!--begin::Card-->
        <div class="card h-100 position-relative">
            <a href="#" 
            class="btn btn-sm btn-danger position-absolute top-0 end-0 m-1 rounded-circle p-3 d-flex align-items-center justify-content-center delete-btn" 
            hx-post="{% url 'delete_file_view' file.id %}"
            hx-trigger="click"
            hx-target="#files-container" >
                <i class="p-0 bi-trash"></i>
            </a>
            <!--end::Delete Button-->
            <!--begin::Card body-->
            <div class="card-body d-flex justify-content-center text-center flex-column p-8">
                <!--begin::Name-->
                <a href="{% url 'download_file' file.id %}" class="text-gray-800 text-hover-primary d-flex flex-column">
                    <!--begin::Image-->
                    <div class="symbol symbol-60px mb-5">
                        {% if file.file_type == '.jpg' or file.file_type == '.jpeg' or file.file_type == '.png' or file.file_type == '.gif' or file.file_type == '.bmp' %}
                            <img src="{% static 'assets/extra_media/svg/files/blank-image-dark.svg' %}" class="theme-light-show" alt="Image">
                            <img src="{% static 'assets/extra_media/svg/files/blank-image-dark.svg' %}" class="theme-dark-show" alt="Image">
                        {% elif file.file_type == '.pdf' %}
                            <img src="{% static 'assets/extra_media/svg/files/pdf.svg' %}" class="theme-light-show" alt="PDF">
                            <img src="{% static 'assets/extra_media/svg/files/pdf-dark.svg' %}" class="theme-dark-show" alt="PDF">
                        {% elif file.file_type == '.doc' or file.file_type == '.docx' %}
                            <img src="{% static 'assets/extra_media/svg/files/doc.svg' %}" class="theme-light-show" alt="DOC">
                            <img src="{% static 'assets/extra_media/svg/files/doc-dark.svg' %}" class="theme-dark-show" alt="DOC">
                        {% else %}
                            <img src="{% static 'assets/extra_media/svg/files/file.svg' %}" class="theme-light-show" alt="File">
                            <img src="{% static 'assets/extra_media/svg/files/file-dark.svg' %}" class="theme-dark-show" alt="File">
                        {% endif %}
                    </div>
                    <!--end::Image-->
                    <!--begin::Title-->
                    <div class="fs-5 fw-bold mb-2">{{ file.file.name|cut:"uploads/"|default:"Unnamed File" }}</div>
                    <!--end::Title-->
                </a>
                <!--end::Name-->
                <!--begin::Description-->
                <div class="fs-7 fw-semibold text-gray-500">
                    Uploaded on: {{ file.process_start_date|date:"F d, Y" }}
                </div>
                <div class="fs-7 fw-semibold text-gray-500">
                    Uploaded by: {{ file.uploaded_by.username }}
                </div>
                <!--end::Description-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Card-->
    </div>
{% endfor %}
{% if paginator.has_next %}
    <div class="d-flex justify-content-center col-12 col-sm-6 col-md-6 col-lg-4"
         hx-get="{% url 'filter_files_view' pk=customer.pk %}?page={{ paginator.next_page_number }}&{{ parameters }}"
         hx-trigger="revealed"
         hx-swap="outerHTML">
        <div class="spinner-border text-primary" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
{% endif %}


<style>
    .delete-btn {
        transition: transform 0.3s ease, background-color 0.3s ease;
    }

    .delete-btn:hover {
        background-color: #dc3545; 
        transform: scale(1.2);
    }
</style>

<script>
    function changeIcon(button) {
        const icon = button.querySelector('i');
        icon.classList.remove('bi-trash');
        icon.classList.add('bi-check-circle');
    }

    function restoreIcon(button) {
        const icon = button.querySelector('i');
        icon.classList.remove('bi-check-circle');
        icon.classList.add('bi-trash');
    }
</script>

templates/pages/customers/actions/components/partials/modal_form.html
<form hx-post="{% url 'upload_file' pk=customer.pk %}" 
                    hx-target="#modal-file-replace" 
                    enctype="multipart/form-data" 
                    method="post">
                        {% csrf_token %}
                        {% comment %} <input type="hidden" name="belongs_to" value="{{ customer.id }}">  <!-- Asociar al cliente actual --> {% endcomment %}
                        <div class="mb-3">
                            <label for="id_file" class="form-label">File</label>
                            <input type="file" name="file" id="id_file" class="form-control">
                            {% if form.file.errors %}
                                <div class="text-danger">{{ form.file.errors.0 }}</div>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <label for="id_process_start_date" class="form-label">Process Start Date</label>
                            <input type="date" name="process_start_date" id="id_process_start_date" class="form-control">
                            {% if form.process_start_date.errors %}
                                <div class="text-danger">{{ form.process_start_date.errors.0 }}</div>
                            {% endif %}
                        </div>

                        {% if tag_message %}
                            <script>                
                                Swal.fire({
                                    position: "top-center",
                                    icon: '{% if "error" in tags %}error{% elif "success" in tags %}success{% elif "info" in tags %}info{% elif "warning" in tags %}warning{% else %}question{% endif %}',
                                    title: "{{tag_message}}",
                                    showConfirmButton: false,
                                    timer: 3000
                                });
                            </script>
                        {% endif %}

                        {% if  message %}
                            <div
                            hx-get="{% url 'filter_files_view' pk=customer.pk %}"
                            hx-target="#files-container"
                            hx-trigger="load"
                            >
                            </div>
                        {% endif %}

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Upload</button>
                        </div>
                    </form>